### ISSUE TITLE
badly handled disconnection in wfd

### ISSUE THREAD

**Issue by jku** [01org/wysiwidi#45]
Disconnecting from the source (android) side makes the sink go belly up:

This is definitely _not_ a pristine source clone from master but I don't think the changes are relevant to this.

```
(gdb) r
Starting program: /home/wysiwidi/src/wysiwidi/sink/sink-test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
* Registering Wifi Display with IE 00000600111C440032
[New Thread 0x7ffff5275700 (LWP 12223)]
[New Thread 0x7ffff4a74700 (LWP 12224)]
[New Thread 0x7fffeffff700 (LWP 12225)]
[New Thread 0x7fffef7fe700 (LWP 12226)]
* New peer: Nexus 5 (jku)
[Thread 0x7ffff5275700 (LWP 12223) exited]
[Thread 0x7ffff4a74700 (LWP 12224) exited]
* Connecting to source at 192.168.3.2:7236
** Message: Trying to connect...
** Message: connection success to: 192.168.3.2
terminate called after throwing an instance of 'std::bad_weak_ptr'
  what():  bad_weak_ptr

Program received signal SIGABRT, Aborted.
0x00007ffff6180107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6180107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff61814e8 in __GI_abort () at abort.c:89
#2  0x00007ffff6c88b3d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6c86bb6 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6c86c01 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6c86e19 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b8993f in std::__throw_bad_weak_ptr ()
    at /usr/include/c++/4.9/bits/shared_ptr_base.h:78
#7  0x00007ffff7b8b7f2 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count (this=0x7fffffffdb98, __r=...)
    at /usr/include/c++/4.9/bits/shared_ptr_base.h:822
#8  0x00007ffff7b8b3f7 in std::__shared_ptr<wfd::MessageHandler, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<wfd::MessageHandler> (
    this=0x7fffffffdb90, __r=...)
    at /usr/include/c++/4.9/bits/shared_ptr_base.h:940
#9  0x00007ffff7b8ac35 in std::shared_ptr<wfd::MessageHandler>::shared_ptr<wfd::MessageHandler> (this=0x7fffffffdb90, 
    __r=std::weak_ptr (empty) 0x0)
    at /usr/include/c++/4.9/bits/shared_ptr.h:249
#10 0x00007ffff7b8a2e9 in std::enable_shared_from_this<wfd::MessageHandler>::shared_from_this (this=0x7fe1e8)
    at /usr/include/c++/4.9/bits/shared_ptr.h:547
#11 0x00007ffff7b87d63 in wfd::MessageSequenceHandler::OnCompleted (
    this=0x7fe1e0, handler=std::shared_ptr (count 3, weak 1) 0x805e50)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:90
#12 0x00007ffff7b87d77 in wfd::MessageSequenceHandler::OnCompleted (
    this=0x805e50, handler=std::shared_ptr (count 3, weak 1) 0x805ed0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:90
#13 0x00007ffff7b88a76 in wfd::MessageSequenceWithOptionalSetHandler::OnCo---Type <return> to continue, or q <return> to quit---
mpleted (this=0x805e50, 
    handler=std::shared_ptr (count 3, weak 1) 0x805ed0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:199
#14 0x00007ffff7b87d77 in wfd::MessageSequenceHandler::OnCompleted (
    this=0x805ed0, handler=std::shared_ptr (count 2, weak 1) 0x805fc0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:90
#15 0x00007ffff7b895f9 in wfd::MessageSenderBase::Handle (this=0x805fc0, 
    message=std::unique_ptr<wfd::Message> containing 0x80b500)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:295
#16 0x00007ffff7b87ab1 in wfd::MessageSequenceHandler::Handle (
    this=0x805ed0, message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:71
#17 0x00007ffff7b87ab1 in wfd::MessageSequenceHandler::Handle (
    this=0x805e50, message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:71
#18 0x00007ffff7b886ac in wfd::MessageSequenceWithOptionalSetHandler::Handle (this=0x805e50, message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:168
#19 0x00007ffff7b87ab1 in wfd::MessageSequenceHandler::Handle (
    this=0x7fe1e0, message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:71
#20 0x00007ffff7b8c7d0 in wfd::SinkImpl::MessageParsed (this=0x7fef90, 
    message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/sink/sink.cpp:167
#21 0x00007ffff7b8bf57 in wfd::RTSPInputHandler::ParsePayload (
    this=0x7fef98)
    at /home/wysiwidi/src/wysiwidi/wfd/common/rtsp_input_handler.cpp:66
#22 0x00007ffff7b8bd54 in wfd::RTSPInputHandler::InputReceived (
    this=0x7fef98, 
    input="RTSP/1.0 200 OK\r\nDate: Mon, 19 Jan 2015 20:04:44 +0000\r\nServer: stagefright/1.2 (Linux;Android 5.0.1)\r\nCSeq: 4\r\nSession: 1745858788;timeout=30\r\nConnection: close\r\n\r\n")
    at /home/wysiwidi/src/wysiwidi/wfd/common/rtsp_input_handler.cpp:40
#23 0x00007ffff7b8c423 in wfd::SinkImpl::RTSPDataReceived (
    this=0x7fef90, 
    message="RTSP/1.0 200 OK\r\nDate: Mon, 19 Jan 2015 20:04:44 +0000\r\nServer: stagefright/1.2 (Linux;Android 5.0.1)\r\nCSeq: 4\r\nSession: 1745858788;timeout=30\r\nConnection: close\r\n\r\n")
    at /home/wysiwidi/src/wysiwidi/wfd/sink/sink.cpp:129
#24 0x000000000042744c in Sink::got_message (this=0x802b10, 
    message="RTSP/1.0 200 OK\r\nDate: Mon, 19 Jan 2015 20:04:44 +0000\r\nServer: stagefright/1.2 (Linux;Android 5.0.1)\r\nCSeq: 4\r\nSession: 1745858788;timeout=30\r\nConnection: close\r\n\r\n")
    at /home/wysiwidi/src/wysiwidi/sink/sink.cpp:33
#25 0x00000000004290cb in MiracBroker::receive_cb (this=0x802b10, fd=7, 
    condition=G_IO_IN)
    at /home/wysiwidi/src/wysiwidi/mirac_network/mirac-broker.cpp:85
#26 0x0000000000428ee6 in MiracBroker::receive_cb (fd=7, 
    condition=G_IO_IN, data_ptr=0x802b10)
    at /home/wysiwidi/src/wysiwidi/mirac_network/mirac-broker.cpp:45
#27 0x00007ffff728db6d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff728df48 in ?? ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff728e272 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x0000000000425dc4 in main (argc=1, argv=0x7fffffffe358)
    at /home/wysiwidi/src/wysiwidi/sink/main.cpp:123
```

**Comment by pozdnyakov** [comment]
https://github.com/01org/wysiwidi/pull/44 should treat it as well
