### ISSUE TITLE
crash in M3 reply  H264Profile handling

### ISSUE THREAD

**Issue by jku** [01org/wysiwidi#51]
100% reproducable with the LG TV (32LN575S-ZE). 

Note that TV can only manage one connection -- after that you need to reboot it to test again :) 

```
desktop-source-test: /home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp:115: EnumType wfd::{anonymous}::MaskToEnum(ArgType, EnumType) [with EnumType = wfd::H264VideoFormat::H264Profile; ArgType = unsigned char]: Assertion `false' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6175107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6175107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff61764e8 in __GI_abort () at abort.c:89
#2  0x00007ffff616e226 in __assert_fail_base (
    fmt=0x7ffff62a4968 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff7ba87d0 "false", 
    file=file@entry=0x7ffff7ba8798 "/home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp", line=line@entry=115, 
    function=function@entry=0x7ffff7ba8b40 <wfd::H264VideoFormat::H264Profile wfd::(anonymous namespace)::MaskToEnum<wfd::H264VideoFormat::H264Profile, unsigned char>(unsigned char, wfd::H264VideoFormat::H264Profile)::__PRETTY_FUNCTION__> "EnumType wfd::{anonymous}::MaskToEnum(ArgType, EnumType) [with EnumType = wfd::H264VideoFormat::H264Profile; ArgType = unsigned char]") at assert.c:92
#3  0x00007ffff616e2d2 in __GI___assert_fail (
    assertion=0x7ffff7ba87d0 "false", 
    file=0x7ffff7ba8798 "/home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp", line=115, 
    function=0x7ffff7ba8b40 <wfd::H264VideoFormat::H264Profile wfd::(anonymous namespace)::MaskToEnum<wfd::H264VideoFormat::H264Profile, unsigned char>(unsigned char, wfd::H264VideoFormat::H264Profile)::__PRETTY_FUNCTION__> "EnumType wfd::{anonymous}::MaskToEnum(ArgType, EnumType) [with EnumType = wfd::H264VideoFormat::H264Profile; ArgType = unsigned char]")
    at assert.c:101
#4  0x00007ffff7b796bb in wfd::(anonymous namespace)::MaskToEnum<wfd::H264VideoFormat::H264Profile, unsigned char> (from=2 '\002', 
    biggest_value=wfd::H264VideoFormat::CBP)
    at /home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp:115
#5  0x00007ffff7b78c18 in wfd::(anonymous namespace)::ToH264Profile (
    profile=2 '\002')
    at /home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp:122
#6  0x00007ffff7b78c57 in wfd::H264Codec::ToVideoFormat (this=0x80fe80)
    at /home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp:133
#7  0x00007ffff7b790ed in wfd::VideoFormats::GetSupportedH264Formats (
    this=0x80fb30)
    at /home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp:210
#8  0x00007ffff7b92441 in wfd::source::M3Handler::HandleReply (
    this=0x80ca30, reply=0x814160)
    at /home/wysiwidi/src/wysiwidi/wfd/source/cap_negotiation_state.cpp:82
#9  0x00007ffff7b819cf in wfd::MessageSenderBase::Handle (this=0x80ca30, 
    message=std::unique_ptr<wfd::Message> containing 0x814160)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:293
#10 0x00007ffff7b7ff2c in wfd::MessageSequenceHandler::Handle (
    this=0x80c9c0, message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:75
#11 0x00007ffff7b7ff2c in wfd::MessageSequenceHandler::Handle (
    this=0x808b00, message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/common/message_handler.cpp:75
#12 0x00007ffff7b90ec8 in wfd::SourceImpl::MessageParsed (this=0x809c60, 
    message=std::unique_ptr<wfd::Message> containing 0x0)
    at /home/wysiwidi/src/wysiwidi/wfd/source/source.cpp:230
#13 0x00007ffff7b8444c in wfd::RTSPInputHandler::ParsePayload (
    this=0x809c68)
    at /home/wysiwidi/src/wysiwidi/wfd/common/rtsp_input_handler.cpp:76
#14 0x00007ffff7b84168 in wfd::RTSPInputHandler::InputReceived (
    this=0x809c68, 
    input="RTSP/1.0 200 OK\r\nCSeq: 2\r\nContent-Type: text/parameters\r\nContent-Length: 276\r\n\r\nwfd_audio_codecs: LPCM 00000003 00, AAC 00000007 00, AC3 00000007 00\r\nwfd_video_formats: 40 00 01 08 0001FFFF 3FFFFFFF 0"...)
    at /home/wysiwidi/src/wysiwidi/wfd/common/rtsp_input_handler.cpp:40
#15 0x00007ffff7b90503 in wfd::SourceImpl::RTSPDataReceived (
    this=0x809c60, 
    message="RTSP/1.0 200 OK\r\nCSeq: 2\r\nContent-Type: text/parameters\r\nContent-Length: 276\r\n\r\nwfd_audio_codecs: LPCM 00000003 00, AAC 00000007 00, AC3 00000007 00\r\nwfd_video_formats: 40 00 01 08 0001FFFF 3FFFFFFF 0"...) at /home/wysiwidi/src/wysiwidi/wfd/source/source.cpp:139
#16 0x000000000042df56 in MiracBrokerSource::got_message (this=0x805500, 
    message="RTSP/1.0 200 OK\r\nCSeq: 2\r\nContent-Type: text/parameters\r\nContent-Length: 276\r\n\r\nwfd_audio_codecs: LPCM 00000003 00, AAC 00000007 00, AC3 00000007 00\r\nwfd_video_formats: 40 00 01 08 0001FFFF 3FFFFFFF 0"...)
    at /home/wysiwidi/src/wysiwidi/desktop_source/mirac_broker_source.cpp:34
#17 0x000000000043044b in MiracBroker::receive_cb (this=0x805500, fd=7, 
    condition=G_IO_IN)
    at /home/wysiwidi/src/wysiwidi/mirac_network/mirac-broker.cpp:85
#18 0x0000000000430266 in MiracBroker::receive_cb (fd=7, 
    condition=G_IO_IN, data_ptr=0x805500)
    at /home/wysiwidi/src/wysiwidi/mirac_network/mirac-broker.cpp:45
#19 0x00007ffff7282b6d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff7282f48 in ?? ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff7283272 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x000000000042b189 in main (argc=1, argv=0x7fffffffe338)
    at /home/wysiwidi/src/wysiwidi/desktop_source/main.cpp:124
```

**Comment by jku** [comment]
I realize I didn't have the latest changes from today -- will re-test

**Comment by jku** [comment]
Yep, todays changes work fine*, thanks!

*) not fine in the sense that TV would show a picture but at least we start streaming
